server:
  port: 8588
spring:
  application:
    name: order-center
  profiles:
    active:
    - default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8582/eureka/
grpc:
  server:
    port: 9900
