server:
  port: 8584
 
spring:
  application:
    name: eurka-client
  profiles:
    active:
    - default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8582/eureka/

      
feign:
  hystrix:
    enabled: true 
  okhttp:
    enabled: true
    