server:
  port: 8500
spring:
  application:
    name: seataUser
  profiles:
    active:
    - default

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forge?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8582/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.seata.user.bean

