server:
  port: 8500
spring:
  application:
    name: seataUser
  profiles:
    active:
    - default

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forge?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: SW7I+Rv68Q8reKY3J7H6dg6GL+EHdvVOLHmNaft3hC8rxU8KvZNW17kSSPEEDvU4Xp0g77PQeIRvg7S9rgN/6g==



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8582/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.seata.user.bean

