server:
  port: 8585
 
spring:
  application:
    name: sentinel-client
  profiles:
    active:
    - default

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8582/eureka/

      
feign:
  hystrix:
    enabled: false
  okhttp:
    enabled: true
  sentinel:
    enabled: true 
