spring:
  profiles: eureka
  application:
    name: spring-cloud-alibaba-dubbo-provider
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

dubbo:
  scan:
    base-packages: com.alibaba.cloud.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 9090
      server: netty
  registry:
    #   The Spring Cloud Dubbo's registry extension
    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#   address: zookeeper://127.0.0.1:2181
feign:
  hystrix:
    enabled: true