server:
  port: 8601

spring:
  application:
    name: actuator-service
  profiles:
    active:
      - default

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: false
          job: spring
          push-rate: 1
          base-url: 192.168.128.138:9090
        step: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8582/eureka/


feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true

      #配置熔断的超时时间
      #hystrix:
      #  command:
      #    default:
      #      execution:
      #        isolation:
      #          thread:
      #            timeoutInMilliseconds: 1
            